export const USER_LOGIN = 'Auth/USER_LOGIN';
export const USER_LOGIN_REQUEST = 'Auth/USER_LOGIN_REQUEST';
export const USER_LOGIN_COMPLETED = 'Auth/USER_LOGIN_COMPLETED';
export const USER_LOGIN_ERROR = 'Auth/USER_LOGIN_ERROR';

export const GET_BATCH_DETAILS = 'DETAILS/GET_BATCH_DETAILS';
export const GET_BATCH_DETAILS_REQUEST = 'DETAILS/GET_BATCH_DETAILS_REQUEST';
export const GET_BATCH_DETAILS_COMPLETED =
  'DETAILS/GET_BATCH_DETAILS_COMPLETED';
export const GET_BATCH_DETAILS_ERROR = 'DETAILS/GET_BATCH_DETAILS_ERROR';
