// SETTINGS
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONT = 'CHANGE_FONT';
export const FORCE_APPEARANCE = 'FORCE_APPEARANCE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SET_MENU = 'SET_MENU';
export const SET_INTRO = 'SET_INTRO';

// AUTH
export const USER_LOGIN = 'Auth/USER_LOGIN';
export const USER_LOGIN_REQUEST = 'Auth/USER_LOGIN_REQUEST';
export const USER_LOGIN_COMPLETED = 'Auth/USER_LOGIN_COMPLETED';
export const USER_LOGIN_ERROR = 'Auth/USER_LOGIN_ERROR';

export const GET_BATCH_DETAILS = 'DETAILS/GET_BATCH_DETAILS';
export const GET_BATCH_DETAILS_REQUEST = 'DETAILS/GET_BATCH_DETAILS_REQUEST';
export const GET_BATCH_DETAILS_COMPLETED =
  'DETAILS/GET_BATCH_DETAILS_COMPLETED';
export const GET_BATCH_DETAILS_ERROR = 'DETAILS/GET_BATCH_DETAILS_ERROR';
